### ISSUE TITLE
About l1config.RPC_URL and GasPrices

### ISSUE THREAD

**Issue by zeroN0de** [initia-labs/OPinit#79]
https://docs.initia.xyz/build-on-initia/deploying-your-own-minitia-layer-2/setting-up#step-2.-launch
as can see from the link above, the 'launch' command supports easy minitia deployment, but there's a problem.

The problem is occurring in L1config.
command : `minitiad launch initiation-1`

1. when querying latest heights, http response is status:403, so creating clients is not done normally and it terminates with error. 
```
Error: error creating clients: failed to query latest heights: error in json rpc client, with http response metadata: (Status: 403 Forbidden, Protocol HTTP/1.1). error unmarshalling: invalid character '<' looking for beginning of value
Error: failed to run launcher step: failed to run lifecycle during ibc step 5: error creating clients: failed to query latest heights: error in json rpc client, with http response metadata: (Status: 403 Forbidden, Protocol HTTP/1.1). error unmarshalling: invalid character '<' looking for beginning of value
```
- OPinit/contrib/launchtools/config.go -> l1config.RPC_URL
I was actually getting a http status 403 error when trying to `curl <providedRPC>/status`.
Modifying the RPC_URL to match the node my team is running on should resolve the above issue.

2. The new gas policy requires fees to be paid with “GAS” tokens. 

> 2024-06-05T11:07:17.286909Z     error   Failed sending cosmos transaction       {"provider_type": "cosmos", "chain_id": "initiation-1", "msg_types": ["/ibc.core.client.v1.MsgCreateClient"], "error": "insufficient fee", "errorVerbose": "insufficient fee\ncosmossdk.io/errors.Wrap\n\tcosmossdk.io/errors@v1.0.1/errors.go:189\ncosmossdk.io/errors.ABCIError\n\tcosmossdk.io/errors@v1.0.1/errors.go:77\ngithub.com/cosmos/relayer/v2/relayer/chains/cosmos.(*CosmosProvider).sdkError\n\tgithub.com/cosmos/relayer/v2@v2.5.2/relayer/chains/cosmos/tx.go:343\ngithub.com/cosmos/relayer/v2/relayer/chains/cosmos.(*CosmosProvider).broadcastTx\n\tgithub.com/cosmos/relayer/v2@v2.5.2/relayer/chains/cosmos/tx.go:379\ngithub.com/cosmos/relayer/v2/relayer/chains/cosmos.(*CosmosProvider).SendMessagesToMempool\n\tgithub.com/cosmos/relayer/v2@v2.5.2/relayer/chains/cosmos/tx.go:185\ngithub.com/cosmos/relayer/v2/relayer/chains/cosmos.(*CosmosProvider).SendMessages.func2\n\tgithub.com/cosmos/relayer/v2@v2.5.2/relayer/chains/cosmos/tx.go:128\ngithub.com/avast/retry-go/v4.Do.func1\n\tgithub.com/avast/retry-go/v4@v4.5.1/retry.go:115\ngithub.com/avast/retry-go/v4.DoWithData[...]\n\tgithub.com/avast/retry-go/v4@v4.5.1/retry.go:179\ngithub.com/avast/retry-go/v4.Do\n\tgithub.com/avast/retry-go/v4@v4.5.1/retry.go:118\ngithub.com/cosmos/relayer/v2/relayer/chains/cosmos.(*CosmosProvider).SendMessages\n\tgithub.com/cosmos/relayer/v2@v2.5.2/relayer/chains/cosmos/tx.go:127\ngithub.com/cosmos/relayer/v2/relayer.CreateClient.func3\n\tgithub.com/cosmos/relayer/v2@v2.5.2/relayer/client.go:239\ngithub.com/avast/retry-go/v4.Do.func1\n\tgithub.com/avast/retry-go/v4@v4.5.1/retry.go:115\ngithub.com/avast/retry-go/v4.DoWithData[...]\n\tgithub.com/avast/retry-go/v4@v4.5.1/retry.go:179\ngithub.com/avast/retry-go/v4.Do\n\tgithub.com/avast/retry-go/v4@v4.5.1/retry.go:118\ngithub.com/cosmos/relayer/v2/relayer.CreateClient\n\tgithub.com/cosmos/relayer/v2@v2.5.2/relayer/client.go:235\ngithub.com/cosmos/relayer/v2/relayer.(*Chain).CreateClients.func5\n\tgithub.com/cosmos/relayer/v2@v2.5.2/relayer/client.go:89\ngolang.org/x/sync/errgroup.(*Group).Go.func1\n\tgolang.org/x/sync@v0.7.0/errgroup/errgroup.go:78\nruntime.goexit\n\truntime/asm_amd64.s:1695"}

- failed sending transaction is done with “insufficient fee” error. This seems to be an overlooked point that the fee should be paid using “GAS” tokens with the new gas policy. You can pay more init, but we don't think regular users will be able to pay this much init.
- OPinit/contrib/launchtools/config.go -> l1config.GasPrices
modified to 0.15uinit -> 0.15move/944f8dd8dc49f96c25fea9849f16436dcfa6d564eec802f3ef7f8b3ea85368ff and it worked fine. 

**This was tested on my local machine with go.mod replace.**

**Comment by beer-1** [comment]
yea that is right steps to solve the problems.

The gas token is temporal solution only for `initiation-1`, so in next testnet, we will have uinit as gas token and this problem will be gone. 

and for the 403 forbidden error, it also should be fixed in next testnet too. Our current service provider does not provide IBC related query and they are trying to fix this problem.

**Comment by JSHan94** [comment]
@zeroN0de Do you need additional help?

**Comment by zeroN0de** [comment]
@JSHan94 I thought the token name 'GAS' might cause confusion for others, and anticipated that the l1_config might inconvenience everyone, so I submitted a PR. I am pleased that the issues seem to have been resolved. Thank you.
